### PR TITLE
Fix typeError error

### LINKED ISSUE #16: TypeError on commit
I was seeing if there were any stories/bugs I could commit against that I'm not supposed to be able to, and for TW-1723 a TypeError exception was thrown.

image

### PR DESCRIPTION
**Pull request by MatthewRadcliffe**
Closes #16

### CODE REVIEW

**Comment by aabenoja** [comment]
Are those binaries supposed to be commited with this?

**Comment by MatthewRadcliffe** [comment]
The binaries should have never been committed to master. Would it have been better to make a separate pull request to remove them?

**Comment by aabenoja** [comment]
Woops, didn't notice they were being removed. (Binaries in pull requests always confuse me :confused:.) It's fine to remove them now, rather than later.

LGTM.

**Comment by MatthewRadcliffe** [comment]
Another typeError issues popped up concerning committing to Deployment Task and Feature Defect. Once the fixes are in this pull request should be ready for merge, but for now I'll edit this to be a WIP pull request.

**Comment by mtscout6** [comment]
LGTM

**Pull request merged**
