### PR TITLE
Updated eslint from 0.24.1 to 1.10.3.

### PR DESCRIPTION
**Pull request by Ixus**

### CODE REVIEW

**Comment by mtscout6** [comment]
When upgrading ESLint to 1.0 there was a change to the default configuration. Can you add support for eslint-config-exhange-solutions?

**Comment by Ixus** [comment]
Do I use react style to install it?

**Comment by mtscout6** [comment]
No React is a front-end only technology. Use the base configuration.

**Comment by Ixus** [comment]
Ya I went ahead and did that and pushed again after fixing most issues, there was a huge amount.

**Comment by mtscout6** [comment]
:+1:

**Pull request merged**
